/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.2/samples
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

dependencies {
  testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
  testRuntimeOnly("org.junit.platform:junit-platform-launcher")

  implementation("org.springframework.boot:spring-boot-starter-web")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  runtimeOnly("org.springframework.boot:spring-boot-devtools")

  implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
  implementation("org.jetbrains.kotlin:kotlin-reflect")
}

repositories {
  mavenCentral()
}

plugins {
  application
  java
  kotlin("jvm") version "1.9.0"
  kotlin("plugin.spring") version "1.9.0"

  id("org.springframework.boot") version "3.1.2"
  id("io.spring.dependency-management") version "1.1.2"
}
apply(plugin = "io.spring.dependency-management")

application {
  // mainClass.set("endgame.Main")
  mainClass.set("endgame.EndgameApplicationKt")
}

tasks.named<Test>("test") {
  useJUnitPlatform()

  maxHeapSize = "1G"

  testLogging {
      events("passed")
  }
}

tasks.withType<KotlinCompile> {
  kotlinOptions {
    freeCompilerArgs += "-Xjsr305=strict"
  }
}
